---
- name: Ensure graphite packages
  apt: pkg={{item}} state=present
  tags: monitoring
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - graphite-carbon
    - graphite-web

- name: drop graphite defaults
  tags: monitoring
  template: dest=/etc/default/graphite-carbon src=graphite-carbon.j2 mode=0644
  notify: restart carbon-cache

- name: drop graphite local_settings.py
  tags: monitoring
  template: dest=/etc/graphite/local_settings.py src=local_settings.py.j2 mode=0644
  notify: restart apache2

- name: drop apache2 graphite config
  tags: monitoring
  template: dest=/etc/apache2/sites-available/graphite src=graphite.j2
  notify: restart apache2

- name: a2enmod wsgi
  tags: monitoring
  command: a2enmod wsgi creates=/etc/apache2/mods-enabled/wsgi.conf
  notify: restart apache2

- name: a2ensite graphite
  tags: monitoring
  command: a2ensite graphite creates=/etc/apache2/sites-enabled/graphite
  notify: restart apache2

- name: a2dissite default
  tags: monitoring
  command: a2dissite default removes=/etc/apache2/sites-enabled/000-default
  notify: restart apache2

- name: Upgrade graphite database versioning
  tags: monitoring
  shell: su -s /bin/bash _graphite -c "graphite-manage syncdb --noinput"